## Automatically generated file. Time of processing: 2022-07-18T21:34:48.509907


from dataclasses import dataclass

@dataclass
class Param:
    number: int
    block0: int
    name: str
    cluster: str
    byteOffset: int
    byteCount: int
    bitOffset: int
    bitCount: int
    recommendedLimits: tuple
    recommendedStep: int
    defaultValue: int
    midiBytes: int
    helpStr: str


Params = [
    Param(0, 0, byteOffset=422, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="Name", cluster="Name", midiBytes=16, helpStr="The name of the tone, as shown in the keyboard front panel.\nCharacters can be any normal ASCII character."),
    Param(1, 0, byteOffset=135, byteCount=1, bitOffset=0, bitCount=4, defaultValue=0, recommendedLimits=(0, 6), recommendedStep=2, name="Timbre", cluster="Wavetable (Sound A)", midiBytes=1, helpStr=""),
    Param(2, 0, byteOffset=130, byteCount=2, bitOffset=0, bitCount=14, defaultValue=1, recommendedLimits=(0, 900), recommendedStep=1, name="Wavetable", cluster="Wavetable (Sound A)", midiBytes=2, helpStr=""),
    Param(3, 0, byteOffset=132, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="Velocity (Sound A)", midiBytes=1, helpStr=""),
    Param(4, 0, byteOffset=133, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Velocity to filter cutoff", cluster="Velocity (Sound A)", midiBytes=1, helpStr=""),
    Param(5, 0, byteOffset=134, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Velocity sense", cluster="Velocity (Sound A)", midiBytes=1, helpStr=""),
    Param(6, 0, byteOffset=2, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(6, 1, byteOffset=6, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(6, 2, byteOffset=10, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(7, 0, byteOffset=0, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="unused time", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(7, 1, byteOffset=4, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(7, 2, byteOffset=8, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time", cluster="Pitch Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(8, 0, byteOffset=124, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="", cluster="Unknown (Sound A)", midiBytes=2, helpStr=""),
    Param(9, 0, byteOffset=125, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="", cluster="Unknown (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 0, byteOffset=14, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 1, byteOffset=18, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 2, byteOffset=22, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 3, byteOffset=26, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 4, byteOffset=30, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 5, byteOffset=34, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(10, 6, byteOffset=38, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 0, byteOffset=12, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 1, byteOffset=16, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 2, byteOffset=20, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 3, byteOffset=24, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 4, byteOffset=28, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 5, byteOffset=32, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(11, 6, byteOffset=36, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Detune Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 0, byteOffset=42, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 1, byteOffset=46, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 2, byteOffset=50, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 3, byteOffset=54, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 4, byteOffset=58, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 5, byteOffset=62, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(12, 6, byteOffset=66, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 0, byteOffset=40, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 1, byteOffset=44, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 2, byteOffset=48, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 3, byteOffset=52, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 4, byteOffset=56, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 5, byteOffset=60, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(13, 6, byteOffset=64, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Unknown Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(14, 0, byteOffset=126, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Cutoff", cluster="Filter (Sound A)", midiBytes=2, helpStr=""),
    Param(15, 0, byteOffset=127, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Resonance", cluster="Filter (Sound A)", midiBytes=2, helpStr=""),
    Param(16, 0, byteOffset=128, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Envelope Multiplier", cluster="Filter (Sound A)", midiBytes=1, helpStr=""),
    Param(17, 0, byteOffset=70, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 1, byteOffset=74, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 2, byteOffset=78, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 3, byteOffset=82, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 4, byteOffset=86, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 5, byteOffset=90, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(17, 6, byteOffset=94, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 0, byteOffset=68, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="unused time", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 1, byteOffset=72, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 2, byteOffset=76, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 3, byteOffset=80, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 4, byteOffset=84, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 5, byteOffset=88, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(18, 6, byteOffset=92, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Filter Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 0, byteOffset=98, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 1, byteOffset=102, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 2, byteOffset=106, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 3, byteOffset=110, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 4, byteOffset=114, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold level", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 5, byteOffset=118, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(19, 6, byteOffset=122, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 0, byteOffset=96, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="unused time", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 1, byteOffset=100, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 2, byteOffset=104, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 3, byteOffset=108, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 4, byteOffset=112, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 5, byteOffset=116, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(20, 6, byteOffset=120, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Gain Envelope (Sound A)", midiBytes=2, helpStr=""),
    Param(21, 0, byteOffset=271, byteCount=1, bitOffset=0, bitCount=4, defaultValue=0, recommendedLimits=(0, 6), recommendedStep=2, name="Timbre", cluster="Wavetable (Sound B)", midiBytes=1, helpStr=""),
    Param(22, 0, byteOffset=266, byteCount=2, bitOffset=0, bitCount=14, defaultValue=1, recommendedLimits=(0, 900), recommendedStep=1, name="Wavetable", cluster="Wavetable (Sound B)", midiBytes=2, helpStr=""),
    Param(23, 0, byteOffset=268, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="Velocity (Sound B)", midiBytes=1, helpStr=""),
    Param(24, 0, byteOffset=269, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Velocity to filter cutoff", cluster="Velocity (Sound B)", midiBytes=1, helpStr=""),
    Param(25, 0, byteOffset=270, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Velocity sense", cluster="Velocity (Sound B)", midiBytes=1, helpStr=""),
    Param(26, 0, byteOffset=138, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(26, 1, byteOffset=142, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(26, 2, byteOffset=146, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr="Units 1/8 semitones"),
    Param(27, 0, byteOffset=136, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="unused time", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(27, 1, byteOffset=140, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(27, 2, byteOffset=144, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time", cluster="Pitch Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(28, 0, byteOffset=260, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="", cluster="Unknown (Sound B)", midiBytes=2, helpStr=""),
    Param(29, 0, byteOffset=261, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="", cluster="Unknown (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 0, byteOffset=150, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 1, byteOffset=154, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 2, byteOffset=158, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 3, byteOffset=162, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 4, byteOffset=166, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 5, byteOffset=170, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(30, 6, byteOffset=174, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 0, byteOffset=148, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 1, byteOffset=152, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 2, byteOffset=156, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 3, byteOffset=160, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 4, byteOffset=164, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 5, byteOffset=168, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(31, 6, byteOffset=172, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Detune Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 0, byteOffset=178, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 1, byteOffset=182, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 2, byteOffset=186, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 3, byteOffset=190, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 4, byteOffset=194, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 5, byteOffset=198, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(32, 6, byteOffset=202, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 0, byteOffset=176, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 1, byteOffset=180, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 2, byteOffset=184, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 3, byteOffset=188, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 4, byteOffset=192, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 5, byteOffset=196, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(33, 6, byteOffset=200, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Unknown Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(34, 0, byteOffset=262, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Cutoff", cluster="Filter (Sound B)", midiBytes=2, helpStr=""),
    Param(35, 0, byteOffset=263, byteCount=1, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Resonance", cluster="Filter (Sound B)", midiBytes=2, helpStr=""),
    Param(36, 0, byteOffset=264, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Envelope Multiplier", cluster="Filter (Sound B)", midiBytes=1, helpStr=""),
    Param(37, 0, byteOffset=206, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 1, byteOffset=210, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 2, byteOffset=214, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 3, byteOffset=218, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 4, byteOffset=222, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 5, byteOffset=226, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(37, 6, byteOffset=230, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 0, byteOffset=204, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 1, byteOffset=208, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 2, byteOffset=212, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 3, byteOffset=216, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 4, byteOffset=220, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 5, byteOffset=224, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(38, 6, byteOffset=228, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Filter Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 0, byteOffset=234, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 1", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 1, byteOffset=238, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 2", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 2, byteOffset=242, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 3", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 3, byteOffset=246, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Attack 4", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 4, byteOffset=250, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Hold", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 5, byteOffset=254, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 1", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(39, 6, byteOffset=258, byteCount=2, bitOffset=0, bitCount=8, defaultValue=128, recommendedLimits=(0, 255), recommendedStep=16, name="Release 2", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 0, byteOffset=232, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Unused time", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 1, byteOffset=236, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 1", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 2, byteOffset=240, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 2", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 3, byteOffset=244, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 3", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 4, byteOffset=248, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Attack time 4", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 5, byteOffset=252, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 1", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(40, 6, byteOffset=256, byteCount=2, bitOffset=0, bitCount=10, defaultValue=512, recommendedLimits=(256, 1023), recommendedStep=64, name="Release time 2", cluster="Gain Envelope (Sound B)", midiBytes=2, helpStr=""),
    Param(41, 0, byteOffset=421, byteCount=1, bitOffset=7, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="Sound B used for note-off", cluster="Octave", midiBytes=1, helpStr=""),
    Param(42, 0, byteOffset=421, byteCount=1, bitOffset=5, bitCount=2, defaultValue=0, recommendedLimits=(0, 2), recommendedStep=1, name="Note off velocity", cluster="Octave", midiBytes=1, helpStr=""),
    Param(43, 0, byteOffset=421, byteCount=1, bitOffset=1, bitCount=3, defaultValue=4, recommendedLimits=(1, 7), recommendedStep=1, name="Octave shift", cluster="Octave", midiBytes=1, helpStr=""),
    Param(44, 0, byteOffset=421, byteCount=1, bitOffset=0, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="Enable DSP", cluster="DSP Chain", midiBytes=1, helpStr=""),
    Param(45, 0, byteOffset=438, byteCount=1, bitOffset=0, bitCount=7, defaultValue=100, recommendedLimits=(0, 127), recommendedStep=16, name="Volume", cluster="Volume", midiBytes=1, helpStr=""),
    Param(46, 0, byteOffset=439, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Volume 2", cluster="Gain", midiBytes=1, helpStr=""),
    Param(47, 0, byteOffset=440, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="Key-follow 1", cluster="Gain", midiBytes=1, helpStr="Relationship between note pitch and volume of the sound. A value of 2 specifies an equal volume for all pitches, and is the default"),
    Param(48, 0, byteOffset=441, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="Key-follow 2", cluster="Gain", midiBytes=1, helpStr="Relationship between note pitch and volume of the sound. A value of 2 specifies an equal volume for all pitches, and is the default"),
    Param(49, 0, byteOffset=442, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(50, 0, byteOffset=443, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(51, 0, byteOffset=444, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(52, 0, byteOffset=445, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(53, 0, byteOffset=446, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(54, 0, byteOffset=447, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="Gain", midiBytes=1, helpStr=""),
    Param(55, 0, byteOffset=420, byteCount=1, bitOffset=7, bitCount=1, defaultValue=1, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(56, 0, byteOffset=272, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="Chorus send", cluster="Effects", midiBytes=1, helpStr=""),
    Param(57, 0, byteOffset=273, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="Reverb send", cluster="Effects", midiBytes=1, helpStr=""),
    Param(58, 0, byteOffset=274, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="Delay send", cluster="Effects", midiBytes=1, helpStr=""),
    Param(59, 0, byteOffset=292, byteCount=1, bitOffset=4, bitCount=4, defaultValue=15, recommendedLimits=(0, 6), recommendedStep=1, name="Vibrato type", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(60, 0, byteOffset=275, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato rate", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(61, 0, byteOffset=276, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato delay", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(62, 0, byteOffset=277, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato rise time", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(63, 0, byteOffset=278, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato depth", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(64, 0, byteOffset=279, byteCount=1, bitOffset=0, bitCount=7, defaultValue=72, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato depth for CC 01 (modulation)", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(65, 0, byteOffset=280, byteCount=1, bitOffset=0, bitCount=7, defaultValue=72, recommendedLimits=(0, 127), recommendedStep=16, name="Vibrato depth for after-touch", cluster="Vibrato", midiBytes=1, helpStr=""),
    Param(66, 0, byteOffset=292, byteCount=1, bitOffset=0, bitCount=4, defaultValue=15, recommendedLimits=(0, 6), recommendedStep=1, name="Tremolo/filter LFO type", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(67, 0, byteOffset=281, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo/filter LFO rate", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(68, 0, byteOffset=282, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Filter LFO delay", cluster="Filter LFO", midiBytes=1, helpStr=""),
    Param(69, 0, byteOffset=283, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Filter LFO rise time", cluster="Filter LFO", midiBytes=1, helpStr=""),
    Param(70, 0, byteOffset=284, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Filter LFO depth", cluster="Filter LFO", midiBytes=1, helpStr=""),
    Param(71, 0, byteOffset=285, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Filter LFO depth for CC 01 (modulation)", cluster="Filter LFO", midiBytes=1, helpStr=""),
    Param(72, 0, byteOffset=286, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Filter LFO depth for after-touch", cluster="Filter LFO", midiBytes=1, helpStr=""),
    Param(73, 0, byteOffset=287, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo delay", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(74, 0, byteOffset=288, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo rise time", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(75, 0, byteOffset=289, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo depth", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(76, 0, byteOffset=290, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo depth for CC 01 (modulation)", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(77, 0, byteOffset=291, byteCount=1, bitOffset=0, bitCount=7, defaultValue=64, recommendedLimits=(0, 127), recommendedStep=16, name="Tremolo depth for after-touch", cluster="Tremolo", midiBytes=1, helpStr=""),
    Param(78, 0, byteOffset=448, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(79, 0, byteOffset=449, byteCount=1, bitOffset=0, bitCount=4, defaultValue=0, recommendedLimits=(0, 15), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(80, 0, byteOffset=420, byteCount=1, bitOffset=3, bitCount=3, defaultValue=0, recommendedLimits=(0, 7), recommendedStep=1, name="Stretch tuning", cluster="Tuning", midiBytes=1, helpStr="Specifies the stretch tuning, a.k.a. Railsback curve. 0 should be used for most instruments, while 1-7 may be suitable for piano or electric piano sounds"),
    Param(81, 0, byteOffset=420, byteCount=1, bitOffset=2, bitCount=1, defaultValue=1, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(82, 0, byteOffset=420, byteCount=1, bitOffset=1, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(83, 0, byteOffset=420, byteCount=1, bitOffset=0, bitCount=1, defaultValue=1, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(84, 0, byteOffset=294, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="DSP chain name", cluster="DSP Chain", midiBytes=16, helpStr="Name of the DSP chain. This is not used for anything and can be set to any string"),
    Param(85, 0, byteOffset=310, byteCount=2, bitOffset=0, bitCount=14, defaultValue=16383, recommendedLimits=(1, 31), recommendedStep=1, name="DSP effect 1", cluster="DSP", midiBytes=2, helpStr=""),
    Param(85, 1, byteOffset=328, byteCount=2, bitOffset=0, bitCount=14, defaultValue=16383, recommendedLimits=(1, 31), recommendedStep=1, name="DSP effect 2", cluster="DSP", midiBytes=2, helpStr=""),
    Param(85, 2, byteOffset=346, byteCount=2, bitOffset=0, bitCount=14, defaultValue=16383, recommendedLimits=(1, 31), recommendedStep=1, name="DSP effect 3", cluster="DSP", midiBytes=2, helpStr=""),
    Param(85, 3, byteOffset=364, byteCount=2, bitOffset=0, bitCount=14, defaultValue=16383, recommendedLimits=(1, 31), recommendedStep=1, name="DSP effect 4", cluster="DSP", midiBytes=2, helpStr=""),
    Param(86, 0, byteOffset=310, byteCount=2, bitOffset=14, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="DSP bypass 1", cluster="DSP", midiBytes=1, helpStr=""),
    Param(86, 1, byteOffset=328, byteCount=2, bitOffset=14, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="DSP bypass 2", cluster="DSP", midiBytes=1, helpStr=""),
    Param(86, 2, byteOffset=346, byteCount=2, bitOffset=14, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="DSP bypass 3", cluster="DSP", midiBytes=1, helpStr=""),
    Param(86, 3, byteOffset=364, byteCount=2, bitOffset=14, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="DSP bypass 4", cluster="DSP", midiBytes=1, helpStr=""),
    Param(87, 0, byteOffset=312, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="DSP parameters 1", cluster="DSP", midiBytes=16, helpStr=""),
    Param(87, 1, byteOffset=330, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="DSP parameters 2", cluster="DSP", midiBytes=16, helpStr=""),
    Param(87, 2, byteOffset=348, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="DSP parameters 3", cluster="DSP", midiBytes=16, helpStr=""),
    Param(87, 3, byteOffset=366, byteCount=16, bitOffset=-1, bitCount=-1, defaultValue=0, recommendedLimits=(-1, -1), recommendedStep=16, name="DSP parameters 4", cluster="DSP", midiBytes=16, helpStr=""),
    Param(88, 0, byteOffset=383, byteCount=1, bitOffset=7, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(89, 0, byteOffset=383, byteCount=1, bitOffset=3, bitCount=2, defaultValue=0, recommendedLimits=(0, 3), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(90, 0, byteOffset=383, byteCount=1, bitOffset=2, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(91, 0, byteOffset=383, byteCount=1, bitOffset=1, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(92, 0, byteOffset=382, byteCount=1, bitOffset=5, bitCount=3, defaultValue=0, recommendedLimits=(0, 7), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(93, 0, byteOffset=384, byteCount=1, bitOffset=0, bitCount=7, defaultValue=100, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(94, 0, byteOffset=382, byteCount=1, bitOffset=3, bitCount=2, defaultValue=0, recommendedLimits=(0, 3), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(95, 0, byteOffset=382, byteCount=1, bitOffset=2, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(96, 0, byteOffset=382, byteCount=1, bitOffset=1, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(97, 0, byteOffset=385, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(98, 0, byteOffset=386, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(99, 0, byteOffset=382, byteCount=1, bitOffset=0, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(100, 0, byteOffset=388, byteCount=4, bitOffset=0, bitCount=32, defaultValue=0, recommendedLimits=(0, 899), recommendedStep=16, name="DSP chain number", cluster="DSP Chain", midiBytes=5, helpStr="Number of the DSP chain. This is not used for anything and can be set to any value"),
    Param(101, 0, byteOffset=392, byteCount=4, bitOffset=0, bitCount=32, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=5, helpStr=""),
    Param(102, 0, byteOffset=396, byteCount=1, bitOffset=0, bitCount=8, defaultValue=0, recommendedLimits=(0, 255), recommendedStep=16, name="", cluster="", midiBytes=2, helpStr=""),
    Param(103, 0, byteOffset=397, byteCount=1, bitOffset=0, bitCount=7, defaultValue=1, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(104, 0, byteOffset=398, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(105, 0, byteOffset=399, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(106, 0, byteOffset=400, byteCount=4, bitOffset=0, bitCount=32, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=5, helpStr=""),
    Param(107, 0, byteOffset=404, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="Portamento time", cluster="Misc.", midiBytes=1, helpStr=""),
    Param(108, 0, byteOffset=405, byteCount=1, bitOffset=0, bitCount=7, defaultValue=4, recommendedLimits=(1, 7), recommendedStep=1, name="Octave shift (keyboard)", cluster="Octave", midiBytes=1, helpStr=""),
    Param(109, 0, byteOffset=406, byteCount=1, bitOffset=0, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="", midiBytes=2, helpStr=""),
    Param(110, 0, byteOffset=407, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(111, 0, byteOffset=408, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(112, 0, byteOffset=409, byteCount=1, bitOffset=0, bitCount=7, defaultValue=0, recommendedLimits=(0, 127), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(113, 0, byteOffset=410, byteCount=1, bitOffset=0, bitCount=4, defaultValue=1, recommendedLimits=(0, 15), recommendedStep=16, name="", cluster="", midiBytes=1, helpStr=""),
    Param(114, 0, byteOffset=410, byteCount=1, bitOffset=4, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="Monophonic", cluster="Misc.", midiBytes=1, helpStr=""),
    Param(115, 0, byteOffset=410, byteCount=1, bitOffset=5, bitCount=1, defaultValue=0, recommendedLimits=(0, 1), recommendedStep=16, name="Sound B used for double-stop", cluster="Misc.", midiBytes=1, helpStr=""),
    Param(116, 0, byteOffset=410, byteCount=1, bitOffset=6, bitCount=2, defaultValue=0, recommendedLimits=(0, 2), recommendedStep=1, name="Portamento", cluster="Misc.", midiBytes=1, helpStr=""),
    Param(117, 0, byteOffset=412, byteCount=1, bitOffset=0, bitCount=4, defaultValue=0, recommendedLimits=(0, 8), recommendedStep=1, name="Type", cluster="Biquad Filter 1", midiBytes=1, helpStr=""),
    Param(117, 1, byteOffset=416, byteCount=1, bitOffset=0, bitCount=4, defaultValue=0, recommendedLimits=(0, 8), recommendedStep=1, name="Type", cluster="Biquad Filter 2", midiBytes=1, helpStr=""),
    Param(118, 0, byteOffset=412, byteCount=2, bitOffset=4, bitCount=6, defaultValue=12, recommendedLimits=(0, 22), recommendedStep=1, name="Parameter 1", cluster="Biquad Filter 1", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls frequency"),
    Param(118, 1, byteOffset=416, byteCount=2, bitOffset=4, bitCount=6, defaultValue=12, recommendedLimits=(0, 22), recommendedStep=1, name="Parameter 1", cluster="Biquad Filter 2", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls frequency"),
    Param(119, 0, byteOffset=413, byteCount=1, bitOffset=2, bitCount=6, defaultValue=12, recommendedLimits=(0, 24), recommendedStep=1, name="Parameter 2", cluster="Biquad Filter 1", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls gain"),
    Param(119, 1, byteOffset=417, byteCount=1, bitOffset=2, bitCount=6, defaultValue=12, recommendedLimits=(0, 24), recommendedStep=1, name="Parameter 2", cluster="Biquad Filter 2", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls gain"),
    Param(120, 0, byteOffset=414, byteCount=1, bitOffset=4, bitCount=4, defaultValue=0, recommendedLimits=(0, 15), recommendedStep=1, name="Parameter 3", cluster="Biquad Filter 1", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls resonance Q-value"),
    Param(120, 1, byteOffset=418, byteCount=1, bitOffset=4, bitCount=4, defaultValue=0, recommendedLimits=(0, 15), recommendedStep=1, name="Parameter 3", cluster="Biquad Filter 2", midiBytes=1, helpStr="Meaning depends on the filter type. Often it controls resonance Q-value"),
    Param(121, 0, byteOffset=414, byteCount=1, bitOffset=3, bitCount=1, defaultValue=1, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="Biquad Filter 1", midiBytes=1, helpStr=""),
    Param(121, 1, byteOffset=418, byteCount=1, bitOffset=3, bitCount=1, defaultValue=1, recommendedLimits=(0, 1), recommendedStep=16, name="", cluster="Biquad Filter 2", midiBytes=1, helpStr=""),
    Param(122, 0, byteOffset=414, byteCount=1, bitOffset=0, bitCount=3, defaultValue=0, recommendedLimits=(0, 7), recommendedStep=16, name="", cluster="Biquad Filter 1", midiBytes=1, helpStr=""),
    Param(122, 1, byteOffset=418, byteCount=1, bitOffset=0, bitCount=3, defaultValue=0, recommendedLimits=(0, 7), recommendedStep=16, name="", cluster="Biquad Filter 2", midiBytes=1, helpStr=""),
    Param(200, 0, byteOffset=450, byteCount=1, bitOffset=0, bitCount=7, defaultValue=127, recommendedLimits=(0, 127), recommendedStep=16, name="Volume 3", cluster="Keyboard only", midiBytes=1, helpStr="Volume of the note.\nOnly notes played on the keyboard are affected by this (not MIDI IN or rhythms)"),
    Param(201, 0, byteOffset=451, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="Key-follow 3", cluster="Keyboard only", midiBytes=1, helpStr="Relationship between note pitch and volume of the sound. A value of 2 specifies an equal volume for all pitches, and is the default.\nOnly notes played on the keyboard are affected by this (not MIDI IN or rhythms)"),
    Param(202, 0, byteOffset=452, byteCount=1, bitOffset=0, bitCount=7, defaultValue=2, recommendedLimits=(0, 126), recommendedStep=1, name="Key-follow 4", cluster="Keyboard only", midiBytes=1, helpStr="Relationship between note pitch and volume of the sound. A value of 2 specifies an equal volume for all pitches, and is the default.\nOnly notes played on the keyboard are affected by this (not MIDI IN or rhythms)"),
]


