name: MSYS-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up MSYS
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout WX
        uses: actions/checkout@v2
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.1.6
          path: wxWidgets-3.1.6
          submodules: 'true'

      - name: Checkout RtMidi
        uses: actions/checkout@v2
        with:
          repository: thestk/rtmidi
          ref: 5.0.0
          path: RtMidi
          submodules: 'false'

      - name: Cache WX
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: $GITHUB_WORKSPACE/wx-build-dir/lib
          key: wx-build-windows
       
      # This must be done as a separate step from the next one
      - name: Setup MSYS
        shell: msys2 {0}
        run: pacman --noconfirm -S base-devel mingw-w64-x86_64-gcc
    
      - name: Build WX
        if: steps.cache-wx.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          mkdir wx-build-dir
          cd wx-build-dir
          ../wxWidgets-3.1.6/configure --without-expat --without-libtiff --disable-shared --with-msw
          make all
      
      - name: Build Sample
        shell: msys2 {0}
        run: |
          cd wx-build-dir/samples/docview
          make all LDFLAGS="-shared"

      - name: Build Tyrant
        shell: msys2 {0}
        run: |
          cd src-cpp
          make all -f Makefile.windows wx_top_builddir=../wx-build-dir top_srcdir=../wxWidgets-3.1.6 rtmidi_srcdir=../RtMidi
