name: MSYS-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-latest

    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Tone Tyrant
        uses: actions/checkout@v2
        with:
          path: tonetyrant
          submodules: 'true'

      # Build our program
      - name: Build Tyrant 64-bit
        id: build-tyrant-x64
        shell: cmd
        run: |
          mkdir tonetyrant\src-cpp\vc_x64_mswu
          echo "Empty 1" > tonetyrant\src-cpp\vc_x64_mswu\tyrant.exe

      # Build our program
      - name: Build Tyrant 32-bit
        id: build-tyrant-x86
        shell: cmd
        run: |
          mkdir tonetyrant\src-cpp\vc_mswu
          echo "Empty 2" > tonetyrant\src-cpp\vc_mswu\tyrant.exe

      # Upload the artifacts
      - uses: actions/upload-artifact@v2
        if: steps.build-tyrant-x64.outcome == 'success'
        with:
          name: tyrant-${{ runner.os }}-64bit-executable-artifact
          path: tonetyrant/src-cpp/vc_x64_mswu/*.exe
      - uses: actions/upload-artifact@v2
        if: steps.build-tyrant-x86.outcome == 'success'
        with:
          name: tyrant-${{ runner.os }}-32bit-executable-artifact
          path: tonetyrant/src-cpp/vc_mswu/*.exe

  release-all:
    runs-on: ubuntu-latest
    needs: [ build-windows ]
    steps:
      - run: |
          echo "${{ github.ref_name }}"
      - uses: actions/download-artifact@v3
        with:
          name: tyrant-Windows-32bit-executable-artifact
          path: windows-all-versions-32bit-executable-${{ github.ref_name }}.zip
      - uses: actions/download-artifact@v3
        with:
          name: tyrant-Windows-64bit-executable-artifact
          path: windows-all-versions-64bit-executable-${{ github.ref_name }}.zip
      - uses: actions/download-artifact@v3
      - run: |
          mv windows-all-versions-32bit-executable-${{ github.ref_name }}.zip windows-all-versions-32bit-executable-${{ github.ref_name }}-windows.zip
          mv windows-all-versions-64bit-executable-${{ github.ref_name }}.zip windows-all-versions-64bit-executable-${{ github.ref_name }}-windows.zip
          ls -l
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./*.*
            *.zip
            windows-all-versions-32bit-executable-${{ github.ref_name }}-windows.zip
            windows-all-versions-64bit-executable-${{ github.ref_name }}-windows.zip
            linux-gtk2-executable-${{ github.ref_name }}.zip
