name: MSYS-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-latest

    env:
      WXWIN: ${{ github.path }}/wxWidgets
      MINGW_W64_MAKE: mingw32-make

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Check MAKE
        shell: cmd
        run: |
          %MINGW_W64_MAKE% -v

      - name: Checkout WX
        uses: actions/checkout@v2
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.2.0
          path: wxWidgets
          submodules: 'true'

      - name: Cache WX 64-bit
        id: cache-wx
        uses: actions/cache@v3
        with:
          path: wxWidgets/lib
          key: wx-3.2-build-lib-${{ runner.os }}-3264bit-static-staticrt-mingw-${{ hashFiles('wxWidgets/lib/config.log') }}
          restore-keys: |
            wx-3.2-build-lib-${{ runner.os }}-3264bit-static-staticrt-mingw-

      # Builds WX static library. The setup_h step seems to be necessary to avoid a random error, and it must be done
      # with only 1 thread. 4 threads are used for other steps.
      - name: Build WX 64-bit
        if: steps.cache-wx.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          chdir "wxWidgets\build\msw"
          %MINGW_W64_MAKE% SHELL=CMD.exe -j4 -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release clean
          %MINGW_W64_MAKE% SHELL=CMD.exe -j1 -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release setup_h
          %MINGW_W64_MAKE% SHELL=CMD.exe -j4 -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release all

      # For fun :)
      - name: Build Sample
        id: build-sample
        shell: cmd
        run: |
          dir "wxWidgets\lib"
          dir "wxWidgets\lib\gcc_lib"
          cd "wxWidgets\samples\docview"
          %MINGW_W64_MAKE% SHELL=CMD.exe -f makefile.gcc BUILD=release all
          dir "wxWidgets\lib"
          dir "wxWidgets\samples\docview"

  release-all:
    runs-on: ubuntu-latest
    needs: [ build-windows ]
    steps:
      - run: |
          echo "${{ github.ref_name }}"
          echo "Eventually, this should upload the artifacts..."

