name: MSYS-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-latest

    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Tone Tyrant
        uses: actions/checkout@v2
        with:
          path: tonetyrant
          submodules: 'true'

      - name: Checkout WX
        uses: actions/checkout@v2
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.1.6
          path: wxWidgets
          submodules: 'true'

      - name: Checkout RtMidi
        uses: actions/checkout@v2
        with:
          repository: thestk/rtmidi
          ref: 5.0.0
          path: RtMidi-5.0.0
          submodules: 'false'
    
      # Builds WX static library
      - name: Build WX 64-bit
        shell: cmd
        run: |
          dir "wxWidgets\build\msw"
          "%MSBUILD_PATH%" "wxWidgets\build\msw\wx_vc17.sln" /Build "Release|x64"
          dir /S "wxWidgets\lib"

      # Build our program
      - name: Build Tyrant 64-bit
        id: build-tyrant
        shell: cmd
        run: |
          dir "tonetyrant\src-cpp"
          SET WX_BUILD_DIR=..\..\wxWidgets\build\msw
          SET RT_MIDI_DIR=..\..\RtMidi-5.0.0
          "%MSBUILD_PATH%" "tonetyrant\src-cpp\tyrant_vc.vcxproj" /Build "Release|x64"
          dir /S "tonetyrant\src-cpp\vc_x64_mswu"

      # Upload the artifact
      - uses: actions/upload-artifact@v2
        if: steps.build-tyrant.outcome == 'success'
        with:
          name: tyrant-${{ runner.os }}-executable-artifact
          path: tonetyrant/src-cpp/vc_x64_mswu/*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: tyrant-${{ runner.os }}-error-log-artifact
          path: tonetyrant/src-cpp/vc_x64_mswu/tyrant/tyrant_vc.log
          
