name: MSYS-Build

env:
  DEVENV: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Tone Tyrant
        uses: actions/checkout@v2
        with:
          path: tonetyrant

      - name: Checkout WX
        uses: actions/checkout@v2
        with:
          repository: WxWidgets/WxWidgets
          ref: v3.1.6
          path: wxWidgets
          submodules: 'true'

      - name: Checkout RtMidi
        uses: actions/checkout@v2
        with:
          repository: thestk/rtmidi
          ref: 5.0.0
          path: RtMidi
          submodules: 'false'
    
      # Builds WX static library
      - name: Build WX
        run: |
          cd wxWidgets\build\msw
          ${{ env.DEVENV }} wx_vc17.sln /Build "Release|Win32"

      # Build our program
      - name: Build Tyrant
        id: build-tyrant
        continue-on-error: true
        run: |
          cd tonetyrant/src-cpp
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" tyrant_vc.vcxproj /Build "Release|x86"

      # Upload the artifact
      - uses: actions/upload-artifact@v2
        if: steps.build-tyrant.outcome == 'success'
        with:
          name: tyrant-${{ runner.os }}-executable-artifact
          path: tonetyrant/src-cpp/vc_mswu/*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: tyrant-${{ runner.os }}-error-log-artifact
          path: tonetyrant/src-cpp/vc_mswu/tyrant/tyrant_vc.exe
          
