# This is a basic workflow for building ToneTyrant

name: Trial

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # ... commented for now ...
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  build-windows:
    # The type of runner that the job will run on. This is Server 2019, corresponding
    # to Windows 10.
    #
    # PyInstaller only builds for the version of windows that's it's built on. That
    # means this will only run on Windows 10/11 64-bit.
    runs-on: windows-2019
    
    # Output is the built executable
    outputs: 
      executable: dist/tyrant.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-rtmidi
          pip install wxPython
          pip install pyinstaller
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Building
          pyinstaller tyrant.spec
      - uses: actions/upload-artifact@v2
        with:
          name: windows-7-executable-artifact
          path: dist/tyrant.exe
